[package]
name = "consortium"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }